name: Build and publish ui-stack image

on:
  push:
    branches:
      - ryardley/438-build-image-merge

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Log into registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Say hello!
      - run: |
          echo "Hello! This was run from commit: $GITHUB_SHA"
